# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  monoVersion: '6_4_0'

steps:

- task: UseDotNet@2
  displayName: Use .Net Core sdk 3.0.x
  inputs:
    packageType: 'sdk'
    version: '3.0.x'

- task: Bash@3
  displayName: Bash script copy Xamarin iOS mono
  inputs:
    targetType: 'inline'
    script: |
      sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(monoVersion)

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.3.1'
  inputs:
    versionSpec: 5.3.1

- task: Boots@1
  displayName: Install Xamarin.iOS Mono 6.4
  inputs:
    uri: 'https://download.mono-project.com/archive/6.4.0/macos-10-universal/MonoFramework-MDK-6.4.0.187.macos10.xamarin.universal.pkg'

- task: MSBuild@1
  displayName: 'Restore Nuget'
  inputs:
    solution: PlanningPoker/PlanningPoker.iOS/PlanningPoker.iOS.csproj
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/t:Restore'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(outputDirectory)'

- task: XamariniOS@2
  inputs:
    solutionFile: 'PlanningPoker/PlanningPoker.iOS/PlanningPoker.iOS.csproj'
    configuration: 'Release'
    packageApp: false
    buildForSimulator: true
    runNugetRestore: false

- task: AppCenterDistribute@3
  displayName: 'Deploy planningpoker.apk to Visual Studio App Center'
  inputs:
    serverEndpoint: 'AppCenter'
    appSlug: '$(appSlug)'
    appFile: '$(outputDirectory)/*.apk'
    buildVersion: '$(Build.BuildId)'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Test'
    destinationType: 'groups'
    isSilent: false