# Planning Poker Pipeline
# Build a Planning Poker project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  monoVersion: '6_4_0'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: Boots@1
  displayName: Install Xamarin.Android Mono
  inputs:
    uri: 'https://download.mono-project.com/archive/6.4.0/macos-10-universal/MonoFramework-MDK-6.4.0.187.macos10.xamarin.universal.pkg'

- task: UseDotNet@2
  displayName: Use .Net Core sdk 3.0.x
  inputs:
    packageType: 'sdk'
    version: '3.0.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(monoVersion)

- task: MSBuild@1
  displayName: 'Restore Nuget'
  inputs:
    solution: PlanningPoker/PlanningPoker.Android/PlanningPoker.Android.csproj
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Restore'

- task: XamarinAndroid@1
  displayName: 'Build PlanningPoker Android'
  inputs:
    projectFile: PlanningPoker/PlanningPoker.Android/PlanningPoker.Android.csproj
    outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
    configuration: '$(BuildConfiguration)'

- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) $(build.binariesdirectory)/$(BuildConfiguration)/*.apk'
  inputs:
    apkFiles: '$(build.binariesdirectory)/$(BuildConfiguration)/*.apk'
    apksignerKeystoreFile: planningpoker.keystore
    apksignerKeystorePassword: planningpoker
    apksignerKeystoreAlias: planningpoker
    apksignerKeyPassword: planningpoker

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)'
  condition: succeededOrFailed()

- task: AppCenterDistribute@3
  displayName: 'Deploy $(System.DefaultWorkingDirectory)/_PlanningPoker-Xamarin.Android-CI/drop/com.flow.planningpoker.apk to Visual Studio App Center'
  inputs:
    serverEndpoint: AppCenter
    appSlug: 'flow/Planning-Poker'
    appFile: '$(build.binariesdirectory)/$(BuildConfiguration)/*.apk'
    symbolsOption: Android
    releaseNotesInput: Test
    isSilent: false