resources:
  repositories:
    - repository: template
      type: github
      name: amonoyflow/xamarin-pipeline-templates
      endpoint: Pipeline_Templates

pool:
  vmImage: 'macos-latest'

variables:
  - group: android-pipeline

stages:
    - stage: Build
      displayName: Build stage
      jobs:
          - template: xamarin-android-build.yml@template
            parameters:
                environment: 'PreProduction'
                buildConfiguration: '$(buildConfiguration)'
                outputDirectory: '$(outputDirectory)'
                keystoreFile: 'planningpoker.keystore'
                keystorePassword: $(keystore.password)
                keystoreAlias: $(keystore.alias)
                keyPassword: $(key.password)
                projectPath: 'PlanningPoker/PlanningPoker.Android/PlanningPoker.Android.csproj'

    - stage: Distribute
      displayName: Distribute stage
      jobs:
        - template: xamarin-android-distribute.yml@template
          parameters:
            environment: PreProduction
            outputDirectory: '$(outputDirectory)'
            appSlug: '$(appSlug)'