resources:
  repositories:
    - repository: templates
      type: github
      name: amonoyflow/xamarin-pipeline-templates
      endpoint: github_service_connection

pool:
  vmImage: 'macos-latest'

variables:
  - group: android-pipeline

stages:
    - stage: Build
      displayName: Build stage
      jobs:
          - template: xamarin-android-build.yml@templates
            parameters:
                environment: 'PreProduction'
                buildConfiguration: '$(buildConfiguration)'
                outputDirectory: '$(outputDirectory)'
                keystoreFile: 'planningpoker.keystore'
                keystorePassword: $(keystore.password)
                keystoreAlias: $(keystore.alias)
                keyPassword: $(key.password)
                projectPath: 'PlanningPoker/PlanningPoker.Android/PlanningPoker.Android.csproj'
                netCoreVersion: '3.0.x'
                nugetVersion: '5.3.1'

    # - stage: Distribute
    #   displayName: Distribute stage
    #   jobs:
    #     - template: xamarin-android-distribute.yml@templates
    #       parameters:
    #         environment: PreProduction
    #         outputDirectory: '$(outputDirectory)'
    #         appSlug: '$(appSlug)'