resources:
  repositories:
    - repository: template_repo
      type: github
      name: amonoyflow/xamarin-pipeline-templates
      endpoint: Pipeline_Templates

variables:
  - group: android-pipeline

stages:
    - stage: Build
      displayName: Build stage
      jobs:
          - template: xamarin-android-build.yml@template_repo
            parameters:
                environment: 'preproduction'
                buildConfiguration: '$(buildConfiguration)'
                outputDirectory: '$(outputDirectory)'
                keystoreFile: 'planningpoker.keystore'
                keystorePassword: $(keystore.password)
                keystoreAlias: $(keystore.alias)
                keyPassword: $(key.password)

    # - stage: Distribute
    #   displayName: Distribute stage
    #   jobs:
    #       - template: xamarin-android-distribute.yml@template_repo
    #         parameters:
    #             env: 'preproduction'
    #             outputDirectory: '$(outputDirectory)'
    #             appSlug: '$(appSlug)'