resources:
  repositories:
    - repository: test
      type: github
      name: amonoyflow/xamarin-pipeline-templates
      ref: refs/tags/v0.1.0
      endpoint: Azure_Pipeline

variables:
  - group: android-pipeline

stages:
    - stage: Build
      displayName: Build stage
      jobs:
          - template: xamarin-android-build.yml
            parameters:
                environment: 'preproduction'
                buildConfiguration: '$(buildConfiguration)'
                outputDirectory: '$(outputDirectory)'
                keystoreFile: 'planningpoker.keystore'
                keystorePassword: $(keystore.password)
                keystoreAlias: $(keystore.alias)
                keyPassword: $(key.password)

    - stage: Distribute
      displayName: Distribute stage
      jobs:
          - template: xamarin-android-distribute.yml
            parameters:
                env: 'preproduction'
                outputDirectory: '$(outputDirectory)'
                appSlug: '$(appSlug)'