resources:
  repositories:
    - repository: templates
      type: github
      name: amonoyflow/xamarin-pipeline-templates
      endpoint: github_service_connection

pool:
  vmImage: 'macos-latest'

variables:
  - group: android-pipeline

stages:
    - stage: Build
      displayName: Build stage
      jobs:
          - template: xamarin-android-build.yml@templates
            parameters:
                projectName: 'planningpoker'
                buildConfiguration: '$(buildConfiguration)'
                outputDirectory: '$(outputDirectory)'
                keystoreFile: 'planningpoker.keystore'
                keystorePassword: $(keystore.password)
                keystoreAlias: $(keystore.alias)
                keyPassword: $(key.password)
                netCoreVersion: '3.0.x'
                nugetVersion: '5.3.1'
                manifestPath: 'PlanningPoker/PlanningPoker.Android/Properties/AndroidManifest.xml'
                version: '$(majorVersion).$(minorVersion).$(Build.BuildId)'

    - stage: Distribute
      displayName: Distribute stage
      jobs:
        - template: xamarin-android-distribute.yml@templates
          parameters:
            projectName: planningpoker
            outputDirectory: '$(outputDirectory)'
            appSlug: '$(appSlug)'